blank_issues_enabled: false
contact_links:
  - name: Groups.io Mailing list
    url: https://groups.io/g/openwebrx
    about: Community mailing list for general user support and other project-related questions and requests